-- Скрипт наката базы данных educat
CREATE DATABASE EDUCAT_DATABASE;

--Таблицы, хранящие информацию о личных кабинетах
-- Личная карточка пользователей
DROP table USERS;
CREATE TABLE USERS
(
  ID              INT PRIMARY KEY,
  FIRST_NAME      VARCHAR(100) NOT NULL,
  SECOND_NAME     VARCHAR(100) NOT NULL,
  MIDDLE_NAME     VARCHAR(100),
  BIRTH_DATE      TIMESTAMP,
  EMAIL           VARCHAR(100) NOT NULL UNIQUE,
  EMAIL_CONFIRMED BOOLEAN      NOT NULL,
  PHONE           VARCHAR(100),
  VK_LINK         VARCHAR(100),
  FB_LINK         VARCHAR(100),
  INSTA_LINK      VARCHAR(100)
);
-- Личный кабинет пользователя
DROP TABLE ACCOUNTS;
CREATE TABLE ACCOUNTS
(
  ID                  INT PRIMARY KEY,
  USERNAME            VARCHAR(100) NOT NULL UNIQUE,
  ACCOUNT_PASSWORD    VARCHAR(100) NOT NULL,
  USER_ID             INT          NOT NULL UNIQUE REFERENCES USERS,
  STATUS              VARCHAR      NOT NULL,
  RATING              VARCHAR,
  CREATION_DATE       TIMESTAMP    NOT NULL,
  LAST_DATE_ON_SYSTEM TIMESTAMP
);
-- Настройки, связанные с кастомизацией личного кабинета
DROP TABLE ACCOUNT_SETTINGS;
CREATE TABLE ACCOUNT_SETTINGS
(
  ID         INT NOT NULL UNIQUE,
  ACCOUNT_ID INT NOT NULL REFERENCES ACCOUNTS,
  PRIMARY KEY (ID, ACCOUNT_ID)
);
-- Роли
DROP TABLE ROLES;
CREATE TABLE ROLES
(
  ID               INT PRIMARY KEY,
  ROLE_NAME        VARCHAR(100) NOT NULL UNIQUE,
  ROLE_DESCRIPTION VARCHAR(100)
);

ALTER TABLE ACCOUNTS
  ADD ACCOUNT_ROLE_ID INT REFERENCES ROLES;

-- Права доступа для ролей
DROP TABLE PERMISSIONS;
CREATE TABLE PERMISSIONS
(
  ID                     INT PRIMARY KEY,
  ROLE_ID                INT          NOT NULL REFERENCES ROLES,
  PERMISSION             VARCHAR(100) NOT NULL,
  PERMISSION_DESCRIPTION VARCHAR(255)
);
-- Аудит изменений, связанных с личным кабинетом
DROP TABLE ACCOUNTS_HISTORY;
CREATE TABLE ACCOUNTS_HISTORY
(
  ID                INT PRIMARY KEY,
  ACCOUNT_ID        INT       NOT NULL REFERENCES ACCOUNTS,
  CHANGED_PARAMETER VARCHAR   NOT NULL,
  PARAMETER_VALUE   VARCHAR   NOT NULL,
  ASSIGNMENT_DATE   TIMESTAMP NOT NULL
);


-- Таблицы связанные с написанием статей/блогов
DROP TABLE ARTICLES;
CREATE TABLE ARTICLES
(
  ID            INT PRIMARY KEY,
  STATUS_ID     INT NOT NULL,
  CREATION_DATE TIMESTAMP,
  HEADER        VARCHAR(300),
  CONTENT       VARCHAR,
  CREATOR_ID    INT NOT NULL REFERENCES ACCOUNTS,
  TAGS          VARCHAR
);


-- Таблицы, связанные с хранением документов и документооборотом
DROP TABLE DOCUMENTS;
CREATE TABLE DOCUMENTS
(
  ID            INT PRIMARY KEY,
  CREATOR_ID    INT REFERENCES ACCOUNTS,
  CREATION_DATE TIMESTAMP    NOT NULL,
  CONTENT       XML          NOT NULL,
  STATUS        VARCHAR(255) NOT NULL
);
-- Тип документа
CREATE TABLE DOCUMENT_TYPE
(
  ID                   INT PRIMARY KEY,
  DOC_TYPE_NAME        VARCHAR NOT NULL,
  DOC_TYPE_DESCRIPTION VARCHAR
);

ALTER TABLE DOCUMENTS ADD DOC_TYPE_ID INT REFERENCES DOCUMENT_TYPE;


-- Таблицы, связанные с задачами, заданиями блока подготовки к экзаменам
-- Категория задач
DROP TABLE TASK_CATEGORIES;
CREATE TABLE TASK_CATEGORIES
(
  ID                   INT PRIMARY KEY,
  CATEGORY_DEFINITION  VARCHAR(255) NOT NULL,
  CATEGORY_DESCRIPTION VARCHAR(255)
);
-- Предметы
DROP TABLE SUBJECTS;
CREATE TABLE SUBJECTS
(
  ID           INT PRIMARY KEY,
  SUBJECT_NAME VARCHAR NOT NULL
);
-- Задачи
DROP TABLE TASKS;
CREATE TABLE TASKS
(
  ID            INT PRIMARY KEY,
  CREATION_DATE TIMESTAMP NOT NULL,
  CONTENT       JSON      NOT NULL,
  ANSWER        JSON      NOT NULL,
  TAGS          VARCHAR(255),
  SUBJECT_ID    INT REFERENCES SUBJECTS,
  CATEGORY_ID   INT REFERENCES TASK_CATEGORIES
);

-- Достижения
DROP TABLE ACHIEVEMENTS;
CREATE TABLE ACHIEVEMENTS
(
  ID          INT PRIMARY KEY,
  NAME        VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  ICON_LINK   VARCHAR(255) NOT NULL
);
-- Достижения, полученные пользователями
DROP TABLE OBTAINED_ACHIEVEMENTS;
CREATE TABLE OBTAINED_ACHIEVEMENTS
(
  ID             INT PRIMARY KEY,
  ACCOUNT_ID     INT REFERENCES ACCOUNTS,
  ACHIEVEMENT_ID INT REFERENCES ACHIEVEMENTS,
  OBTAIN_DATE    TIMESTAMP NOT NULL
);
-- Тестовые варианты
DROP TABLE TRAINING_JOBS;
CREATE TABLE TRAINING_JOBS
(
  ID         INT NOT NULL,
  JOB_ID     INT NOT NULL,
  TASK_ID    INT NOT NULL REFERENCES TASKS,
  SUBJECT_ID INT NOT NULL REFERENCES SUBJECTS
);


-- Конфигурационные, админские таблицы
DROP TABLE CONFIGURES;
CREATE TABLE CONFIGURES
(
  ID          INT          NOT NULL,
  NAME        VARCHAR(255) NOT NULL UNIQUE,
  VALUE       VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID, NAME)
);
